import './globals.scss';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Karla } from 'next/font/google';
import '/node_modules/react-grid-layout/css/styles.css';
import '/node_modules/react-resizable/css/styles.css';
import './styles.scss';

const karla = Karla({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="">
			<body className={`${karla.className} round bg-slate-1 dark`} suppressHydrationWarning={true}>
				{children}
			</body>
		</html>
	);
}

// mr-[calc(-1*(100vw-100%))]
